#!/bin/perl

use strict;
use warnings;
use 5.010;

my $rep_list_file = $ARGV[0];
my @reps;
my $link_prefix = "https://api.opendota.com/api/matches/";
open REPS, "<", $rep_list_file;

while (<REPS>) {
  chomp;
  my $rep_id = $_;
  my $link = $link_prefix . $rep_id;
  `wget -q $link`;
  open MATCH_DETAIL, "<", $rep_id or die "can't open file $rep_id";
  my $url;
  while (<MATCH_DETAIL>) {
    if (m!"replay_url":"(http://.*.bz2)"!) {
      $url = $1;
      last;
    }
  }
  close MATCH_DETAIL;
  `wget -q $url`;
  $url =~ m!/(\w*.dem.bz2)!;
  `bzip2 -d $1`;
  my $file_name = $1;
  $file_name =~ m/(\A.*.dem)/;
  $file_name = $1;
  my $new_file_name;
  $file_name =~ m/\A(\d*)_\d*.dem/;
  $new_file_name = $1 . ".dem";
  `rm $rep_id`;
  `mv $file_name $new_file_name`;
}

close REPS;
